---
- hosts: webservers
  become: yes
  tasks:
  - name: Install Java (Debian)
    apt:
     name: default-jdk
     update_cache: yes
     state: present
    when: ansible_distribution == "Debian"

  - name: Install Java (Amazon Linux)
    dnf:
     name: java-11-amazon-corretto-headless
     state: present
    when: ansible_distribution == "Amazon"

  - name: Install Java (Red Hat)
    yum:
      name: java-11-openjdk
      state: present
    when: ansible_distribution == "RedHat"

  - name: Install Tomcat (Debian)
    apt:
      name: tomcat10
      state: present
    when: ansible_distribution == "Debian"

  - name: Install Tomcat (Amazon Linux)
    dnf:
      name: tomcat9
      state: present
    when: ansible_distribution == "Amazon"
    vars:
      ansible_python_interpreter: /usr/bin/python3
      
  - name: Install Tomcat (Red Hat)
    yum:
      name: tomcat
      state: present
    when: ansible_distribution == "RedHat"
   
  - name: Install Maven (Debian)
    apt:
      name: maven
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Install Maven (RedHat)
    yum:
      name: maven
      state: present
    when: ansible_distribution == "RedHat"

  - name: Start Tomcat (Debian)
    service:
      name: tomcat10
      state: started
    when: ansible_distribution == "Debian"

  - name: Start Tomcat (Red Hat)
    service:
      name: tomcat
      state: started
    when: ansible_distribution == "RedHat"

  - name: Start Tomcat (Amazon Linux)
    service:
      name: tomcat9
      state: started
    when: ansible_distribution == "Amazon"

  - name: Enable Tomcat (Debian)
    service:
      name: tomcat10
      state: enabled
    when: ansible_distribution == "Debian"

  - name: Enable Tomcat (Red Hat)
    service:
      name: tomcat
      state: enabled
    when: ansible_distribution == "RedHat"

  - name: Enable Tomcat (Amazon Linux)
    service:
      name: tomcat9
      state: enabled
    when: ansible_distribution == "Amazon"

  - name: Clone Java Web Calculator
    git:
      repo: 'https://github.com/lizbabz/JavaCalculator.git'
      dest: "/var/lib/tomcat{{ '9' if ansible_distribution == 'Amazon' else '' }}/webapps/JavaWebCalculator"

  - name: Clone Java Web Calculator
    git:
      repo: 'https://github.com/lizbabz/JavaCalculator.git'
      dest: "/var/lib/tomcat{{ '10' if ansible_distribution == 'Debian' else '' }}/webapps/JavaWebCalculator"
...
